[theme]
base="light"
primaryColor="#228B22"          # forest green for buttons, accents
backgroundColor="#FFFFFF"       # white
secondaryBackgroundColor="#F0F2F6"  # light grey
textColor="#000000"             # black
font="sans serif"
